# Generated by Django 3.2.12 on 2022-02-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
                ('due_data', models.DateField()),
                ('tag', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('WORKING', 'WORKING'), (
                    'DONE', 'DONE'), ('OVERDUE', 'OVERDUE')], max_length=7)),
            ],
        ),
    ]
