# Generated by Django 3.2.12 on 2022-02-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220223_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
