# Generated by Django 3.2.12 on 2022-02-23 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_task_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
